# Generated by Django 4.2 on 2023-06-26 00:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('SUPERADMIN', 'SuperAdmin'), ('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('RECEPTION', 'Reception'), ('INTERN', 'Intern'), ('PATIENT', 'Patient'), ('COLAB', 'Colab'), ('TRAINEE', 'Trainee'), ('EMPLOYEE', 'Employee')], default='EMPLOYEE', max_length=50, unique=True),
        ),
    ]
