# Generated by Django 4.2 on 2023-06-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_role_role'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.CheckConstraint(check=models.Q(('role__in', ['SUPERADMIN', 'ADMIN', 'DOCTOR', 'NURSE', 'RECEPTION', 'INTERN', 'PATIENT', 'COLAB', 'TRAINEE', 'EMPLOYEE'])), name='users_role_role_valid'),
        ),
    ]
