version: '3.9'

services:
  web:
    build: 
      context: .
    restart: always
    env_file:
      - ./app/dev.env
    volumes:
      - static-data:/vol/web
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devDB
      - POSTGRES_USER=devUser
      - POSTGRES_PASSWORD=devPassword

volumes:
  postgres-data:
  static-data: