version: '3.9'

services:
  web:
    build: .
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./app/dev.env
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    depends_on:
      - db
  
  db:
    image: postgres:15-alpine
    hostname: devdbhost
    environment:
      - POSTGRES_DB=devDB
      - POSTGRES_USER=devUser
      - POSTGRES_PASSWORD=devPassword
  
  